version: '3.8'

services:
  flask:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./flask:/app
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/app